title: The Journal of Peace and Development
description: Madal cilmiyeed madax-bannaan oo diiradda saarta nabadda, horumarka dhaqaalaha, iyo maamul wanaagga Soomaaliya iyo Geeska Afrika.
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:
