title: The Journal of Peace and Development
description: Fostering Stability through Governance and Progress
theme: jekyll-theme-cayman
nav:
  - text: Home
    href: index.html
  - text: Editorial Board
    href: EDITORIAL-BOARD.html
  - text: Guidelines
    href: AUTHOR-GUIDELINES.html
  - text: Ethics
    href: ETHICS-STATEMENT.html
  - text: Archives
    href: ARCHIVE.html
  - text: Submissions
    href: submission.html
